### ISSUE TITLE
The cookie settings button is not visible even though cookie_settings_button_enabled is true

### ISSUE THREAD

**Issue by teshiba** [MrGreensWorkshop/MrGreen-JekyllTheme#104]
### Please check these items before go any further

- [X] I have watched [Mr. Green theme tutorials playlist](https://www.youtube.com/playlist?list=PLAymxPbYHgl-fFy5can7uZBMJtFWVcphD) on YouTube.
- [X] I have searched the existing [Issues](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/issues/).
- [X] I have searched the existing [Discussions](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/discussions).
- [X] I have checked [jekyll docs](https://jekyllrb.com/docs/) and the answer was not there.
- [X] I have tested in one of these browsers; Safari, Chrome, Firefox. (This project hasn't been tested in other browsers.)

### Are you sure this is a bug?

- [X] I'm sure this is definitely a bug.

### Describe the bug

If color_scheme_switch_side_nav is false, side-nav-bottom-buttons-container is not displayed.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/570665d929690e5c0a3b01c24a5079ec6bc3324a/_includes/default/nav/navigation-side-nav-bottom-buttons.html

Therefore even though cookie_settings_button_enabled is true, the cookie setting button is also not displayed.

### Expected Behavior

If  color_scheme_switch_side_nav is true or cookie_settings_button_enabled is true then 
side-nav-bottom-buttons-container is visible.

![image](https://user-images.githubusercontent.com/35426691/183279248-553efadf-68b2-4184-ad51-c43edaf374b1.png)

### Steps To Reproduce

1.  Set `color_scheme_switch_side_nav` to `false` in _data\conf\main.yml
2.  Run `bundle exec jekyll serve --baseurl ""` on a terminal.
3. browse `http://127.0.0.1:4000/`
![image](https://user-images.githubusercontent.com/35426691/183278929-a920dee6-d0af-4be9-975c-8c908ee559e8.png)

4. It can not display the cookie settings button.

### Which browser have you used?

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Other browsers (This project hasn't been tested in other browsers.)

### Which device have you used?

- [X] Desktop
- [ ] Mobile IOS
- [ ] Mobile Android
- [ ] Other platforms (This project hasn't been tested in other devices.)

### Anything else?

In the `_includes\default\nav\navigation-side-nav-bottom-buttons.html`
change the code as follows. It works I expected.
```diff
-{% if color_scheme_switch_enabled == true %}
+{% if color_scheme_switch_enabled == true or cookie_settings_button_enabled == true %}
  <div class="side-nav-bottom-buttons-container">
```
I have already fixed it so that I can pull request.

**Comment by MrGreensWorkshop** [comment]
Hi, you are right. Thank you, PR that please.

**Comment by MrGreensWorkshop** [comment]
merged, Thanks again.
