### ISSUE TITLE
Mastodon icon for contacts links

### ISSUE THREAD

**Issue by MrGreensWorkshop** [MrGreensWorkshop/MrGreen-JekyllTheme#126]
### Is this enhancement or feature is related to a problem?

I think it's better to have the mastodon icon for the contact option.

### Describe the solution you'd like

Since the mastodon icon is not available in [Font Awesome 4.7.0](https://fontawesome.com/v4/icons/), I added an svg file for it.

The mastodon icon was obtained from [mastodon repo](https://github.com/mastodon/joinmastodon/blob/master/public/logos/logo-black.svg)

### Describe alternatives you've considered

none

### Additional context

none

**Comment by MrGreensWorkshop** [comment]
This is how it looks after adding the icon.
<img width="235" alt="Screenshot 2022-12-11 at 17 34 31" src="https://user-images.githubusercontent.com/76992231/206894049-f4740e5a-b9e0-4b61-a8c7-478e1fc85a2a.png">

**Comment by MrGreensWorkshop** [comment]
@joshbuker 

Hi, I added a contact link icon for mastodon to the theme. I thought you might want to know.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/issues/126

*I will delete this msg after you read.

**Comment by joshbuker** [comment]
@MrGreensWorkshop Would it be possible to update the `rel` attribute to include `me`? This is used for verification on Mastodon.

e.g.
```html
<a href="https://example.com/@example" rel="me noopener noreferrer">Mastodon</a>
```
