### ISSUE TITLE
Mastodon, identity verification feature

### ISSUE THREAD

**Issue by MrGreensWorkshop** [MrGreensWorkshop/MrGreen-JekyllTheme#130]
### Is this enhancement or feature is related to a problem?

Mastodon uses identity verification which uses links. it is better to have it.

### Describe the solution you'd like

How to do so is described [here](https://docs.joinmastodon.org/user/profile/#verification).

**Comment by MrGreensWorkshop** [comment]
form @joshbuker 
@MrGreensWorkshop Would it be possible to update the `rel` attribute to include `me`? This is used for verification on Mastodon.

e.g.
```html
<a href="https://example.com/@example" rel="me noopener noreferrer">Mastodon</a>
```

**Comment by MrGreensWorkshop** [comment]
@joshbuker Consider it done! 
How do you feel about enabling or disabling the rel="me" option in owner/en.yml? Do you think it's too much?

**Comment by joshbuker** [comment]
I don't think it would cause problems if you permanently enabled the feature, but having it be a setting would be fine too. Whatever you think makes more sense. :slightly_smiling_face:

**Comment by MrGreensWorkshop** [comment]
What I mean is, since the verification is so easy, someone could use it for bad purposes and write down someone's account. I'm always skeptical about these extreme easy verification things. I thought it was better to have two actions. I think I will add that option in, [here](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/main/_data/conf/main.yml#L217).

To verify, I wish there was a DNS text record check. 😞

**Comment by MrGreensWorkshop** [comment]
feature added and tested.
