### ISSUE TITLE
Contact form using Google Forms.

### ISSUE THREAD

**Issue by MrGreensWorkshop** [MrGreensWorkshop/MrGreen-JekyllTheme#143]
### Is this enhancement or feature is related to a problem?

I think we need contact form and this is what I came up with.

### Describe the solution you'd like

There are other options to but for personal use, I think Google Forms will be sufficient.

This is the "Contact Form" button added after the about text; it is added to_layouts/about.md.

<img width="893" alt="button" src="https://user-images.githubusercontent.com/76992231/208352622-0c83b46b-bcd4-45e7-bda5-57cec677785c.png">

This is the loading text that appears until the Google Form is loaded. 

<img width="1047" alt="loading" src="https://user-images.githubusercontent.com/76992231/208352613-0b6d6e66-7002-4927-84ef-e2233141018a.png">

This is the Google Form that has been loaded. 

<img width="1047" alt="form" src="https://user-images.githubusercontent.com/76992231/208352631-c84cfaac-a25e-4620-a747-8d2599cf39e7.png">

### Describe alternatives you've considered

https://formspree.io/plans
https://formspark.io/pricing

### Additional context

How to use?

It is explained in these files. Search for "contact_form" in both these files: `_data/owner/[language].yml` and `_data/conf/main.yml`.

**Comment by MrGreensWorkshop** [comment]
@fandangos Hi, sorry to bother you like this. Could you please take a look at the comments at PR #143, where I mentioned your name, and tell me what you think? Thanks in advance.

**Comment by fandangos** [comment]
No bothering at all, glad to help in whatever I can. 

Are we talking about this P`R? 
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/pull/144/commits/53e15a12159d5b0fdca2a2e59f4f1a887beba76e

I see just a few lines in portuguese and those are OK to understand, minor tweaks could improve it but it's fine as it is. 
If you want I can provide a translation to this paragraph:
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/pull/144/commits/53e15a12159d5b0fdca2a2e59f4f1a887beba76e#diff-95836f60c62131324ab103bf9d6682c429cab8acc6814c780c70acfcf591c8abR73

But it needs to get merged first so I know how's the final text that needs translation. 

Let me know what I can do to help and I'll do it.

**Comment by MrGreensWorkshop** [comment]
@fandangos  Thank you alright I think I will merge this so you can send a PR to repo.

**Comment by MrGreensWorkshop** [comment]
@fandangos 
These are the parts that are involved.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/commit/53e15a12159d5b0fdca2a2e59f4f1a887beba76e#r93608375

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/commit/53e15a12159d5b0fdca2a2e59f4f1a887beba76e#r93608329

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/commit/53e15a12159d5b0fdca2a2e59f4f1a887beba76e#r93608345

**Comment by fandangos** [comment]
Great! Having the directions to what needs to be translated makes things much faster. 

My family is here for dinner, can't do it today.
I'll do it tomorrow after breakfast.

**Comment by MrGreensWorkshop** [comment]
This issue is finished, as the feature was made in PR #144 and the Brazilian Portuguese translations were checked and improved by @fandangos in PR #145.
