### ISSUE TITLE
Korean language support.

### ISSUE THREAD

**Issue by MrGreensWorkshop** [MrGreensWorkshop/MrGreen-JekyllTheme#177]
### Is this enhancement or feature is related to a problem?

**Public message for anyone who speaks Korean.**

I intend to add Korean language support. I've already translated everything, but I need volunteers to double-check the translations. Could you please take a look and check if these translations are okay?

line, 4
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_language_support/ko/_posts/2023-02-19-mr-green-jekyll-theme.markdown?plain=1#L4

line 5,11,45
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_language_support/_data/owner/ko.yml

line, 7,8,15,18,21,28,29,176,177,189,210,218,226
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_language_support/_data/content/projects/ko.yml

line, 44,45,52,55,65,71,73,75,77,79,81,83,85,87,93
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_language_support/ko/tabs/links.md?plain=1

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_language_support/_data/lang/ko.yml

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_language_support/README-ko.md

If you think there is a mistake in the translation, please let me know by commenting on this issue, or you can submit a PR targeted to the this branch [`feature_korean_language_support`](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/tree/feature_korean_support).

Thanks in advance.

### Describe the solution you'd like

Adding Korean Language

**Comment by MrGreensWorkshop** [comment]
@fandangos Hi,
This time, I'm going to add Korean, and I need your advice because I need to add language lists to all Readme files. Is it okay to say Coreano for Korean, as shown below?

[readme file](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/README-pt.md)
`Inglês (padrão), Japonês, Português do Brasil, Coreano`

Thanks in advance.

**Comment by MrGreensWorkshop** [comment]
**Public message for anyone who speaks Korean.**

I intend to add Korean language support; I've prepared a draft in [this branch](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/tree/feature_korean_lang). Could you please take a look and check if these translations are okay?

line, 4
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/ko/_posts/2023-02-19-mr-green-jekyll-theme.markdown?plain=1

line 5,11,45
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/_data/owner/ko.yml

line, 7,8,15,18,21,28,29,176,177,189,210,218,226
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/_data/content/projects/ko.yml

line, 44,45,52,55,65,71,73,75,77,79,81,83,85,87,93
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/ko/tabs/links.md?plain=1

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/_data/lang/ko.yml

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/README-ko.md

**Comment by fandangos** [comment]
> @fandangos Hi, I'm going to add Korean language support, and I need your advice because I need to add language lists to all Readme files. Is it okay to say Coreano or Coreana for Korean, as shown below?
> 
> [readme file](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/README-pt.md) `Inglês (padrão), Japonês, Português do Brasil, Coreano`
> 
> Thanks in advance.

The correct is Coreano as you are referencing the language, in Portuguese it's referencing to "idioma" and while it ends in a which would be feminine we refer to it using masculine article "O".
Ex: O português e O coreanO because it's O idioma Coreano.

Sorry for the late reply and hope the explanation is clear enough to help here.

**Comment by MrGreensWorkshop** [comment]
> > @fandangos Hi, I'm going to add Korean language support, and I need your advice because I need to add language lists to all Readme files. Is it okay to say Coreano or Coreana for Korean, as shown below?
> > [readme file](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_korean_lang/README-pt.md) `Inglês (padrão), Japonês, Português do Brasil, Coreano`
> > Thanks in advance.
> 
> The correct is Coreano as you are referencing the language, in Portuguese it's referencing to "idioma" and while it ends in a which would be feminine we refer to it using masculine article "O". Ex: O português e O coreanO because it's O idioma Coreano.
> 
> Sorry for the late reply and hope the explanation is clear enough to help here.

@fandangos 
Thank you for your explanation. It's rock solid.

**Comment by MrGreensWorkshop** [comment]
Since French is added. I need to make some updates on this.

**Comment by MrGreensWorkshop** [comment]
I asked for a double check, but I didn't get many returns. I will go with the current state. There is always room for improvement. Please feel free to correct any of my mistakes.
