### ISSUE TITLE
French language support

### ISSUE THREAD

**Issue by MrGreensWorkshop** [MrGreensWorkshop/MrGreen-JekyllTheme#181]
### Is this enhancement or feature is related to a problem?

French language translations.

### Describe the solution you'd like

French language translations.

**Comment by MrGreensWorkshop** [comment]
line, 4
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/ko/_posts/2023-02-19-mr-green-jekyll-theme.markdown?plain=1#L4

line 5,11,45
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/owner/ko.yml

line, 7,8,15,18,21,28,29,176,177,189,210,218,226
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/content/projects/ko.yml

line, 44,45,52,55,65,71,73,75,77,79,81,83,85,87,93
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/ko/tabs/links.md?plain=1

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/ko.yml

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/README-ko.md


If you think there is a mistake in the translation, please let me know by commenting on this issue, or you can send a PR targeted to the `feature_french_lang` branch.

Thanks in advance.

**Comment by MrGreensWorkshop** [comment]
line, 4
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/fr/_posts/2023-02-19-mr-green-jekyll-theme.markdown?plain=1#L4

line 5,11,45
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/owner/fr.yml

line, 7,8,15,18,21,28,29,176,177,189,210,218,226
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/content/projects/fr.yml

line, 44,45,52,55,65,71,73,75,77,79,81,83,85,87,93
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/fr/tabs/links.md?plain=1

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

Almost all lines
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/README-fr.md


If you think there is a mistake in the translation, please let me know by commenting on this issue, or you can send a PR targeted to the `feature_french_lang` branch.

Thanks in advance.

**Comment by JPMorissette** [comment]
line, 75
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/fr/tabs/links.md?plain=1

"Il y a tellement de variables et de filtres Jekyll à retenir et il peut être difficile de tout garder en tête. Cette feuille de triche sert de référence rapide de tout ce que Jekyll peut faire."

Should be:

"Il y a tellement de variables et de filtres Jekyll à retenir qu'il peut être difficile de tout garder en tête. Cette feuille aide-mémoire sert de référence rapide de tout ce que Jekyll peut faire."

**Comment by JPMorissette** [comment]
line, 79
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/fr/tabs/links.md?plain=1

"Wiki Liquid for Designers sur GitHub."

Should be:

"Wiki Liquid pour les Designers sur GitHub"

**Comment by JPMorissette** [comment]
line, 79
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/fr/tabs/links.md?plain=1

"Liquid est un langage de modèle créé par Shopify et écrit en Ruby. Il est maintenant disponible en tant que projet open source sur GitHub."

Should be:

"Liquid est un langage de gabarit créé par Shopify et écrit en Ruby. Il est maintenant disponible en tant que projet open source sur GitHub."

**Comment by JPMorissette** [comment]
line, 76
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

first_post: "D'abord"

Should be

first_post: "Début"

**Comment by JPMorissette** [comment]
line, 93
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

load_and_do_not_ask_again: Montre toujours

Should be

load_and_do_not_ask_again: Toujours montrer

**Comment by JPMorissette** [comment]
line, 124
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

        clear: Claire

Should be:

clear: Effacer

(I'm not sure what this "clear" means. It is clear as in erase? If so, Effacer will be fine.)

**Comment by JPMorissette** [comment]
line, 129
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

tags: Étiqueter

Should be 

tags: Étiquette

**Comment by JPMorissette** [comment]
line, 138
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml
 
button_name: Maison

Should be:

button_name: Accueil

**Comment by JPMorissette** [comment]
line, 166
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

read_less_text: Lire moins

Should be:

read_less_text: Réduire

**Comment by JPMorissette** [comment]
line, 175
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

  welcome: Bienvenu

Should be:

welcome: Bienvenue

**Comment by JPMorissette** [comment]
line, 190
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

Il sera activé avec votre accord.

Should be:

Ils seront activés avec votre accord.

**Comment by JPMorissette** [comment]
line, 200
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml

      Il sera activé avec votre accord. Veuillez cliquer sur chaque élément ci-dessous pour la politique en matière de cookies.

Should be:

Ils seront activés avec votre accord. Veuillez cliquer sur chaque élément ci-dessous pour la politique en matière de cookies.

**Comment by MrGreensWorkshop** [comment]
> line, 124 https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml
> 
> ```
>     clear: Claire
> ```
> 
> Should be:
> 
> clear: Effacer
> 
> (I'm not sure what this "clear" means. It is clear as in erase? If so, Effacer will be fine.)

The tag filter is cleared when you click the "Clear" button. So which one would be better?

**Comment by MrGreensWorkshop** [comment]
> line, 175 https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml
> 
> welcome: Bienvenu
> 
> Should be:
> 
> welcome: Bienvenue

Line 137 as well?

**Comment by JPMorissette** [comment]
line, 20
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/README-fr.md

  <a href="https://jekyll-theme-mrgreen-demo.mrgreensworkshop.com" style="font-weight: bold;" >Cliquez ici pour une démo en direct</a>

Should be:

  <a href="https://jekyll-theme-mrgreen-demo.mrgreensworkshop.com" style="font-weight: bold;" >Cliquez ici pour voir un exemple en ligne</a>

**Comment by JPMorissette** [comment]
line, 12
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/README-fr.md

[<img src="https://shields.io/badge/Patreon-Support%20me-blue?logo=Patreon" alt="Soyez mon patron" data-no-image-viewer>](https://patreon.com/MrGreensWorkshop "Soyez mon patron")

Should be:

[<img src="https://shields.io/badge/Patreon-Support%20me-blue?logo=Patreon" alt="Soyez un de mes patreons" data-no-image-viewer>](https://patreon.com/MrGreensWorkshop "Soyez un de mes patreons")

**Comment by MrGreensWorkshop** [comment]
> line, 124 https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml
> 
> ```
>     clear: Claire
> ```
> 
> Should be:
> 
> clear: Effacer
> 
> (I'm not sure what this "clear" means. It is clear as in erase? If so, Effacer will be fine.)

The tag filter is cleared when you click the "Clear" button. So which one would be better?

> line, 175 https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml
> 
> welcome: Bienvenu
> 
> Should be:
> 
> welcome: Bienvenue

Line 137 as well?

other then that I updated the files Thanks to you.

I also added a copyright notice here.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/_data/lang/fr.yml#L3

also added to the contributors.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README.md?plain=1#L122

**Comment by JPMorissette** [comment]
> > line, 124 https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml
> > ```
> >     clear: Claire
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Should be:
> > clear: Effacer
> > (I'm not sure what this "clear" means. It is clear as in erase? If so, Effacer will be fine.)
> 
> The tag filter is cleared when you click the "Clear" button. So which one would be better?

In that case, it should be "Retirer".

> > line, 175 https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/feature_french_lang/_data/lang/fr.yml
> > welcome: Bienvenu
> > Should be:
> > welcome: Bienvenue
> 
> Line 137 as well?

Yes, although Line 137 seems fine already. (Or you may have changed it already)

> other then that I updated the files Thanks to you.
> 
> I also added a copyright notice here.
> 
> https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/_data/lang/fr.yml#L3
> 
> also added to the contributors for all languages. For French readme files, how about "Corrections de la traduction française par Jean-Philippe Morissette."?

Yes, that is perfect!

> https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README.md?plain=1#L122
> 
> Thanks in advance.

**Comment by MrGreensWorkshop** [comment]
Also added to the contributors for all languages. This is for French.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/4ca89171b7ea39e03a9c444f86a53d0090fca805/README-fr.md?plain=1#L122

Please let me know when your check is finished.
Thanks in advance.

**Comment by MrGreensWorkshop** [comment]
@fandangos Hi, I'm planning to add these translations to the Portuguese readme. Please let me know what you think.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README.md?plain=1#L122

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README-pt.md?plain=1#L122

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README-pt.md?plain=1#L37

**Comment by JPMorissette** [comment]
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/edit/feature_french_lang/README-fr.md

line, 32
J'allais créer mon site Web et je pensais que si je le faisais comme modèle, je pourrais le partager avec la communauté open source. C'est pourquoi j'ai décidé de le construire comme thème. J'ai travaillé si dur pour rendre cela possible, alors s'il vous plaît, pensez à [soutenir mon travail](#vous-pouvez-soutenir-mon-travail). Merci.
Should be:
J'allais créer mon site Web et j'ai pensé que si je le faisais en tant que gabarit, je pourrais le partager avec la communauté open source. C'est pourquoi j'ai décidé de le construire comme thème. J'ai travaillé si dur pour rendre cela possible, alors s'il vous plaît, pensez à [soutenir mon travail](#vous-pouvez-soutenir-mon-travail). Merci.

line, 38
- Fonction d'offre de langue recommandée
Should be
- Fonction de suggestion de langue

line, 39
- Additionneur de bouton de navigation automatique avec icône activer désactiver les options
Should be
- Ajout de boutons de navigation automatique avec icône, options d'activation et de désactivation.

line, 42-44
- Additif d'option de contact automatique
- Référentiel d'image automatique (inutile d'ajouter un chemin complet pour les images. Ajoutez`:` le simplement devant.)
- Chargeur paresseux d'images, visionneuse d'images
Should be:
- Ajout d'option de contact automatique
- Référentiel d'image automatique (inutile d'ajouter un chemin complet pour les images. Ajoutez simplement `:` devant.)
- Chargement différé d'images, visionneuse d'images

line, 46
- Boîte modale de table des matières mobile pour les messages
Should be:
- Boîte modale de table des matières mobile pour les publications

line, 48-49
- Post-listing par catégorie ou tags
- Commentaires pour les messages
Should be:
- Liste des publications par catégorie ou étiquettes
- Commentaires pour les publications

line, 52
- Pagination numérotée sélectionnable ou défilement pour charger le type
Should be:
- Sélection entre une pagination numérotée ou un chargement via défilement

line, 61-62
- Fonction de recherche de sites
- Code Compression pour faible encombrement (`HTML` `JS` `SCSS`)
Should be:
- Fonction de recherche sur le site
- Compression de code pour faible encombrement (`HTML` `JS` `SCSS`)

line, 71
1. [Fourchez le dépôt](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/fork).
Should be:
1. [Dupliquer le dépôt](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/fork).

line, 79
1. Vérifiez `Actions` l'onglet État du déploiement sur le référentiel.
Should be:
1. Vérifiez l'état du déploiement dans l'onglet `Actions` de votre dépot.

line 85, 89
1. Clonez ou [téléchargez](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/releases/latest) le référentiel, dans l'invite de commande, accédez à la `bundle install` commande d'exécution du dossier
1. Construire à l'aide `bundle exec jekyll serve --watch --host 0.0.0.0 --safe` de la commande,
    - avec `--host 0.0.0.0` le paramètre, vous pouvez accéder au serveur Web à partir du même réseau local.
    - avec `--safe` le paramètre, vous pouvez vous assurer qu'aucun plugin tiers n'a été ajouté. (pour le développement de pages GitHub)
1. Votre page sera opérationnelle à l' `0.0.0.0:4000/` adresse.
Should be:
1. Clonez ou [téléchargez](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/releases/latest) le dépot, accédez à votre répertoire dans l'invite de commande puis exécuter la commande `bundle install`.
1. Construire votre site à l'aide de la commande `bundle exec jekyll serve --watch --host 0.0.0.0 --safe`,
    - avec le paramètre `--host 0.0.0.0`, vous pouvez accéder au serveur Web à partir de votre réseau local.
    - avec le paramètre`--safe`, vous pouvez vous assurer qu'aucun plugin tiers n'a été ajouté. (pour le développement de pages GitHub)
1. Votre page sera opérationnelle à l'adresse `0.0.0.0:4000/`.

line, 107
Créer des projets à partir de rien prend beaucoup de temps. Très apprécié si vous envisagez de me soutenir afin que je puisse continuer des projets comme celui-ci et créer de nouveaux contenus pour tout le monde.
Should be:
Créer des projets à partir de rien prend beaucoup de temps. Je serais reconnaissant que vous envisagiez me soutenir afin que je puisse continuer des projets comme celui-ci et  que je puisse créer de nouveaux contenus pour tout le monde.

line, 115
Les demandes d'extraction sont les bienvenues. Veuillez vérifier les instructions dans les modèles de problèmes et de demande d'extraction.
Should be:
Les demandes de tirage (pull requests) sont les bienvenues. Veuillez vérifier les instructions dans les modèles de problèmes et de demande de tirage.

line, 129
Veuillez ajouter un lien vers ma page ou laisser le lien "Pwrd by Mr. Green" dans le pied de page afin que je puisse obtenir un crédit pour mon travail.
Should be:
Veuillez ajouter un lien vers ma page ou laisser le lien "Pwrd by Mr. Green" dans le pied de page afin que je puisse obtenir du crédit pour mon travail.

line, 137
| Library                              | file |
Should be:
| Bibliothèque                              | fichier |

**Comment by JPMorissette** [comment]
I think I'm done.

I'll most likely fork from this new build of yours. If I ever find typos, what should I do? Pull/Push requests?

**Comment by MrGreensWorkshop** [comment]
@JPMorissette Thank you so much for your time and effort. I'll merge into the main branch once the Portuguese check is completed. Of course, if you want to make an enhancement, feel free to submit a PR. Please post a question in the Discussions if you need help building your site.

In addition, every now and then, I'll make some changes, such as adding a new language or a new feature, and so on. Is it okay to poke you and ask for your check?

 Thanks in advance.

**Comment by MrGreensWorkshop** [comment]
@fandangos Could you please check this too?
> @fandangos Hi, I'm planning to add these translations to the Portuguese readme. Please let me know what you think.
> 
> https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README.md?plain=1#L122
> 
> https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README-pt.md?plain=1#L122
> 
> https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README-pt.md?plain=1#L37

**Comment by MrGreensWorkshop** [comment]
@fandangos Hi, I'm planning to add these translations to the Portuguese readme. Please let me know what you think.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README.md?plain=1#L122

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README-pt.md?plain=1#L122

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/ed53e53771af75aad869f242b39e780023885388/README-pt.md?plain=1#L37

**Comment by fandangos** [comment]
I would change "Correções da tradução francesa por... " for "Correções da tradução para o francês por..."

**Comment by MrGreensWorkshop** [comment]
@JPMorissette I'm sorry I forgot to ask you last thing as you may know I need some translations for [demo page to show](https://jekyll-theme-mrgreen-demo.mrgreensworkshop.com/).

could you please check these are appropriate?

Jekyll theme  -> Thème Jekyll
Welcome to Mr. Green Theme.  -> Bienvenue à Thème de Mr. Green.
Awesome jekyll theme -> Thème jekyll génial

Mr. Green is a multilingual theme generated with Jekyll and fully compatible with GitHub Pages.  -> Mr. Green est un thème multilingue généré avec Jekyll et entièrement compatible avec les pages GitHub.
Sample post (auto generated)  -> Exemple de message (généré automatiquement)
Hello!  -> Bonjour !
Learn More.   ->  Apprendre encore plus.
This is an auto generated sample content for display in the selected language.   -> Il s'agit d'un exemple de contenu généré automatiquement pour l'affichage dans la langue sélectionnée.

Thanks in advance.

**Comment by JPMorissette** [comment]
Hello @MrGreensWorkshop ,

I would change 

Welcome to Mr. Green Theme. -> Bienvenue à Thème de Mr. Green. ("Bienvenue à" as the first line and "Thème de Mr. Green" as the second line)

to 

Welcome to Mr. Green Theme. -> Bienvenue sur le site du Thème de Mr. Green. 

Otherwise, everything seems perfect!

**Comment by MrGreensWorkshop** [comment]
@JPMorissette Thank you for your time and effort. The demo site is up and running now.
https://jekyll-theme-mrgreen-demo.mrgreensworkshop.com/fr/
