### ISSUE TITLE
Copyright note for the translation files.

### ISSUE THREAD

**Issue by MrGreensWorkshop** [MrGreensWorkshop/MrGreen-JekyllTheme#184]
### Is this enhancement or feature is related to a problem?

Since translations were made, I want to give credit its authors.

### Describe the solution you'd like

 I will add copyright note at the top of it.

### Additional context

Affected files
[_data/lang](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/tree/main/_data/lang)

**Comment by MrGreensWorkshop** [comment]
@fandangos Hi, I added copyright note to the translations, is it ok?
I can put your website(https://fandangos.github.io) instead of https://github.com/fandangos please let me know what do you thing.

https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/89745e8b2446957f32e96806c55808194b326f4e/_data/lang/pt.yml#L1-L4

**Comment by fandangos** [comment]
> @fandangos Hi, I have added copyright note to all [translation files](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/tree/main/_data/lang). I can put your website (https://fandangos.github.io) instead of https://github.com/fandangos. Please let me know what you think. ↓↓
> 
> https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/89745e8b2446957f32e96806c55808194b326f4e/_data/lang/pt.yml#L1-L4

I'm very sorry for the late reply. 
Pointing to my Github instead of the blog is better in my opinion. 
Thank you for the consideration doing so and glad I could help with this amazing project.

**Comment by MrGreensWorkshop** [comment]
@fandangos You are welcome. Well then I will leave as is. Thank you.

**Comment by MrGreensWorkshop** [comment]
#185 is merged. I'm closing this issue.
