### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by onurergunay** [MrGreensWorkshop/MrGreen-JekyllTheme#232]
### Is this enhancement or feature is related to a problem?

This is a language enhancement for the theme.

### Describe the solution you'd like

I wanted to add Turkish language support.

**Comment by MrGreensWorkshop** [comment]
Hi, @onurergunay 
It looks fabulous. Thanks again for your time. For the last time, may I kindly ask you to make these changes?

- Please add a copyright note at the beginning of the /_data/lang/tr.yml file. (please check fr.yml or pt.yml) I will add a thank you message to all readme files for adding Turkish language support.

- As you may know I need some translations for [demo page to show](https://jekyll-theme-mrgreen-demo.mrgreensworkshop.com/).
You only need to write it down here so I can take care of it while building the demo page.

```
Jekyll theme -> 
Welcome to Mr. Green Theme. ->  (please divide into 2 lines.)
Awesome jekyll theme -> 
Mr. Green is a multilingual theme generated with Jekyll and fully compatible with GitHub Pages. -> 
Sample post (auto generated) -> 
Hello! -> 
Learn More. -> 
This is an auto generated sample content for display in the selected language. -> 
```

Thanks in advance.

**Comment by onurergunay** [comment]
Hi, Thanks to you.

- I added copyright note to the  /_data/lang/tr.yml file. 
- Please check out the translations below.

Jekyll theme -> `Jekyll teması`
Welcome to Mr. Green Theme. ->  (please divide into 2 lines.) 
1st line -> `Mr. Green temasına`
2nd line -> `Hoşgeldiniz`
Awesome jekyll theme -> `Müthiş jekyll teması`
Mr. Green is a multilingual theme generated with Jekyll and fully compatible with GitHub Pages. -> 
`Mr. Green, Jekyll ile oluşturulmuş ve GitHub Pages ile tamamen uyumlu çok dilli bir temadır.`
Sample post (auto generated) -> `Örnek makale (otomatik oluşturuldu)`
Hello! ->  `Merhaba!`
Learn More. ->  `Daha fazla bilgi için.`
This is an auto generated sample content for display in the selected language. -> 
`Bu içerik, seçilen dilde görüntülenmek üzere otomatik oluşturulmuş bir örnektir.`

If you need anything else, please let me know.

**Comment by MrGreensWorkshop** [comment]
How does it look?

- Turkish translation by [Onur Ergünay](https://github.com/onurergunay).

**Comment by onurergunay** [comment]
LGTM. Thanks.

**Comment by MrGreensWorkshop** [comment]
@onurergunay I fixed a few things in the readme file.
Thank you for your time and effort. The demo site is up and running now.
https://jekyll-theme-mrgreen-demo.mrgreensworkshop.com/tr/
