### ISSUE TITLE
Trying to add FR lang

### ISSUE THREAD

**Issue by SofianeBoumedine** [MrGreensWorkshop/MrGreen-JekyllTheme#28]
Hi, I tried to add FR Language but it make duplicate content and duplicate menu, seems not to work. Instead I respect the ISO Code:
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
https://en.wikipedia.org/wiki/ISO_3166-2
**Describe the bug**

- I create a file fr.yml in the /_data/lang
- I delete the ja.yml
- Replace the "ja" by "fr" in the files main.yml like that: `language_switch_lang_list: [en, fr]`
- Results it make duplicate content/menu and the switch language disappear:
<img width="1440" alt="Capture d’écran 2022-05-10 à 15 22 17" src="https://user-images.githubusercontent.com/18581295/167638419-6af2c5e0-4e93-47e8-a1de-cae4c0f57970.png">
 
When I rollback and replace by jp no issues.

what the plugins used for the multilanguage ?

Thanks in advance for the help and thanks for this JAMSTACK themes

**Comment by MrGreensWorkshop** [comment]
@SofianeBoumedine,
Hi, please watch the video below. I think you can find a solution for your problem.
[How to add a language to multilingual website theme Mr. Green](https://www.youtube.com/watch?v=uoOztMxksHw)

btw, about "JAMSTACK themes" They just introduce themes created by various people like myself. It has nothing to do with development of this theme. (Mr. Green Theme made by me :))

**Comment by SofianeBoumedine** [comment]
https://www.youtube.com/watch?v=uoOztMxksHw&list=PLAymxPbYHgl-fFy5can7uZBMJtFWVcphD&index=3 
Mybad I just found your videos, followed this and it's work.

And yes I know that but it's particular good themes in the wild that we can found.

Thanks for the reactivity we can close the issues :)
