### ISSUE TITLE
How to change main languge English to Japanese

### ISSUE THREAD

**Issue by puraminy** [MrGreensWorkshop/MrGreen-JekyllTheme#86]
I cloned your project and changed main.yml to include only `ja` language as defalut with no langauge list. However the side nav shows two home and other items, one without ja and with it. 
I don't want any link to english pages and just ja folder, and it's the expected behaviour

I attached a screen shot of duplicate entries

![aaaa](https://user-images.githubusercontent.com/5293185/178716363-0067ae64-fd1e-4ccf-8ce6-18e73efb52fe.png)

**Comment by MrGreensWorkshop** [comment]
yes it is expected behavior. To change main language,
just copy all of file and folders inside jp folder to outside of jp folder. overwrite all.

**Comment by MrGreensWorkshop** [comment]
if this helped please feel free to close the issue.

**Comment by puraminy** [comment]
yes, thanks, it resolved the problem
