### ISSUE TITLE
duplicate entry in side nav

### ISSUE THREAD

**Issue by puraminy** [MrGreensWorkshop/MrGreen-JekyllTheme#87]
I cloned your project and changed main.yml to include only `ja` language as defalut with no langauge list. However the side nav shows two home and other items, one without ja and with it. 
I don't want any link to english pages and just ja folder, and it's the expected behaviour

I attached a screen shot of duplicate entries
![aaaa](https://user-images.githubusercontent.com/5293185/178716363-0067ae64-fd1e-4ccf-8ce6-18e73efb52fe.png)

**Comment by MrGreensWorkshop** [comment]
duplicated issue entry I will respond in #86 .
