### ISSUE TITLE
Couldn't find the issue you created? probably moved to Discussions.

### ISSUE THREAD

**Issue by MrGreensWorkshop** [MrGreensWorkshop/MrGreen-JekyllTheme#93]
Couldn't find the issue you created? probably moved to [Discussions](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/discussions).

**Comment by MrGreensWorkshop** [comment]
@joshbuker I already spend lots of time for you, still, I will explain why,

There wasn't a bug in this repo, and you didn't check if it is reproducible in this repo or not but still created an issue. And made me check if there was a problem on this repo. Then I gave you step-by-step instruction, still you made a mistake forget deleting the TR folder. You made me check again and I did, There was't a problem on this repo code at all. 

You had a problem because, you deleted lng_pair: That's on you. You shouldn't delete it, but still did.

This is explained right here.
How to make a multilingual Website or Blog in less than 10 minutes 
https://www.youtube.com/watch?v=U7ryXlWI1mY&t=197s

Before you blame the main repo, check the code differences you already made. Like any programmers would do, Then check if was reproducible or not, if its then create an issue. If you are not sure, use discussions and ask a question. Please don't waste others time.

Some one already have similar problems with yours. Having Two home buttons like yours,
https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/discussions/89

Your issue only served you and wasn't a main repo bug also there is already a same problem exist in discussions, that's why I deleted the issue. I will delete these comments too. Because it's off topic. I hope you got it. 

Please feel free to stop sponsoring me. If you don't understand the code please do not use it.
If you still want to use it and have problem, then use discussions.
Thank you.

**Comment by joshbuker** [comment]
You know what, fair enough. Sorry for wasting your time. I'll refrain from interacting further.
